name=ASM_Usart
version=1.0.1
author=Norman Dunbar <norman@dunbar-it.co.uk>
maintainer=Norman Dunbar <norman@dunbar-it.co.uk>
sentence=USART transmit routines for Assembly Language code.
paragraph=This library provides a 9600 baud USART transmit only function for use in Arduino Assembly Language code.
category=Communication
url=
depends=
includes=ASM_Usart.h
architectures=avr
dot_a_linkage=true
