name=LCDLibrary
version=1.0.2
author=Norman Dunbar <norman@dunbar-it.co.uk>
maintainer=Norman Dunbar <norman@dunbar-it.co.uk>
sentence=LCD handling functions for Assembly Language code.
paragraph=This library provides a wide range of text handling and control functions for use in Arduino Assembly Language code to interface with a 16x2 LCD display in 4 bit mode.
category=Display
url=
depends=
includes=LCDLibrary.h
architectures=avr
dot_a_linkage=true
